### ISSUE TITLE
Issue with selenium webdriver on mac when using capture-full-replay.sh

### ISSUE THREAD

**Issue by abdelYAICHI** [trahay/bbb-downloader#28]
I have this issue when using capture-full-replay.sh on mac OSX,

Can any one help please :(

Thanks in advance

Please wait for 4288 seconds, while we capture the playback...

/Users/user/node_modules/selenium-webdriver/lib/error.js:539
    let err = new ctor(data.message)
              ^

NoSuchElementError: Unable to locate element: .acorn-play-button
    at Object.throwDecodedError (/Users/user/node_modules/selenium-webdriver/lib/error.js:539:15)
    at parseHttpResponse (/Users/user/node_modules/selenium-webdriver/lib/http.js:647:13)
    at Executor.execute (/Users/user/node_modules/selenium-webdriver/lib/http.js:573:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async thenableWebDriverProxy.execute (/Users/user/node_modules/selenium-webdriver/lib/webdriver.js:735:17)
    at async toWireValue (/Users/user/node_modules/selenium-webdriver/lib/webdriver.js:140:15)
    at async /Users/user/node_modules/selenium-webdriver/lib/webdriver.js:190:16
    at async forEachKey (/Users/user/node_modules/selenium-webdriver/lib/webdriver.js:184:9)
    at async convertKeys (/Users/user/node_modules/selenium-webdriver/lib/webdriver.js:189:3)
    at async thenableWebDriverProxy.execute (/Users/user/node_modules/selenium-webdriver/lib/webdriver.js:733:22) {
  remoteStacktrace: 'WebDriverError@chrome://marionette/content/error.js:181:5\n' +
    'NoSuchElementError@chrome://marionette/content/error.js:393:5\n' +
    'element.find/</<@chrome://marionette/content/element.js:306:16\n'
}

**Comment by trahay** [comment]
It looks like depending on the BBB version of the server, the "play" button may be named differently. Commit #2298971 should fix this problem.

**Comment by abdelYAICHI** [comment]
Thank you trahay for your reponse, i added your suggestion but still have another error : 

Please wait for 4288 seconds, while we capture the playback...

/Users/user/node_modules/selenium-webdriver/lib/error.js:575
        throw new ctor(message)
              ^

TimeoutError: Connection refused (os error 111)
Build info: version: '3.141.59', revision: '82b03c358b', time: '2019-04-30T22:04:50'
System info: host: '72b305726f04', ip: '172.17.0.6', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.76-linuxkit', java.version: '1.8.0_292'
Driver info: driver.version: unknown
remote stacktrace: 
    at Object.checkLegacyResponse (/Users/user/node_modules/selenium-webdriver/lib/error.js:575:15)
    at parseHttpResponse (/Users/user/node_modules/selenium-webdriver/lib/http.js:639:13)
    at Executor.execute (/Users/user/node_modules/selenium-webdriver/lib/http.js:573:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  remoteStacktrace: ''

Can you check please and thank you in advance for your help.
